### ISSUE TITLE
403 403 Forbidden

### ISSUE THREAD

**Issue by cherif-bayo** [LaravelDaily/Laravel-Support-Ticketing#1]
Trying to connect to agent1@agent1.com and a get : 403
403 Forbidden
and -> DataTables warning: table id=DataTables_Table_0 - Ajax error. For more information about this error, please see http://datatables.net/tn/7

**Comment by PovilasKorop** [comment]
@cherif-bayo 
1. what did you change in the code? 
2. What URL exactly gives you 403?
3. Check your `storage/logs/laravel.log` - it should show exact Datatables error.

**Comment by cherif-bayo** [comment]
@PovilasKorop 
 
I modified my users table but already fixed the issue 😁. Thanks for this package 👌.

I would like to know if it is possible to add a wysiwyg field for comment on ticket show and ticket edit so that we can attach file if needed ?

**Comment by PovilasKorop** [comment]
@cherif-bayo possible, but we're not planning to do it. If you manage to do it, we will accept a Pull Request :)
