### ISSUE TITLE
Images are not being saved to the database (media table)

### ISSUE THREAD

**Issue by bbroger1** [LaravelDaily/Laravel-Support-Ticketing#14]
I'm testing the Quick Admin Panel and the images I upload when creating the ticket are not being saved in the database, being available only in storage/uploads
![show_ticket](https://user-images.githubusercontent.com/62220624/163681272-4afb66ef-f41b-4201-9520-c3d6810bdd52.PNG)
![bd](https://user-images.githubusercontent.com/62220624/163681275-6d3f513b-517a-4368-bdb6-b284f90dd88e.PNG)
![storage_uploads](https://user-images.githubusercontent.com/62220624/163681276-c5407989-1b43-4050-9a75-7feb969014d0.PNG)

**Comment by PovilasKorop** [comment]
@bbroger1 are you talking about this particular repository, or you're doing the same in the official quickadminpanel.com generator? If it's this demo repository, it may be incomplete with all features.

**Comment by bbroger1** [comment]
Povilas, thanks for the feedback. I'm evaluating this repository. In this case, the problem was that the data for sending communications had not been included and the spatie package needs to be returned to the tickets page to process the sending of images to the definitive repository

**Comment by PovilasKorop** [comment]
@bbroger1 so you've fixed the issue? Then close the issue here on Github, please.
