### ISSUE TITLE
File: 2019_11_10_000001_create_media_table.php

### ISSUE THREAD

**Issue by ghost** [LaravelDaily/Laravel-Support-Ticketing#3]
When executing the "**command php artisan migrate --seed**" the following error message appears (see picture)
![Error](https://user-images.githubusercontent.com/58852447/75340180-4b4c9100-5892-11ea-8846-1eef49b59ef7.JPG)

**Comment by PovilasKorop** [comment]
@veritexx Your database does not support JSON field type that we use for uploading files, as part of Spatie Media Library package. You should use MySQL 5.7.8+ or MariaDB 10.2.7+
