### ISSUE TITLE
Support with this sofware

### ISSUE THREAD

**Issue by MikeyUko** [LaravelDaily/Laravel-Support-Ticketing#9]
Hello, firstly I would like to commend the team who put this up together. Brilliant work and creative minds. However, I encountered some challenges and i'll try to state them with check boxes:

- [ ] I get an error when trying to submit a new ticket: {Swift_TransportException. Cannot send message without a sender address}. I'll attach a screenshot to show this error.

- [ ]  Secondly, I would need help creating a menu for REPORTING on the dashboard, where I can download it as excel, pdf or any other format 

- [x] I would like to change the LARAVEL showing at the top left corner of the application with something of my preferred choice. If I can get directions as to where to see the code for that, I would be grateful 

- [ ]  I would also like to have an image on the login screen as well as the page where the user has to submit a ticket as well as have a logo on the header.
I would really appreciate help with the stated issues

![header](https://user-images.githubusercontent.com/47743663/96718960-ac385480-13a0-11eb-8e0e-8e1c6367464b.jpg)
![error](https://user-images.githubusercontent.com/47743663/96718968-ae9aae80-13a0-11eb-9e9d-0cef6db395fe.jpg)

**Comment by PovilasKorop** [comment]
@MikeyUko "Swift_TransportException" - you need to configure your email client, in `.env` and `config/mail.php`

Everything else is customization work, we don't provide help with customization, this project is open-source, which means you can write that code and contribute to this project as open-source.

**Comment by MikeyUko** [comment]
Thank you very much. I am new to all of this and it is my time working on a project like this, hence my curiosity

**Comment by MikeyUko** [comment]
I still cannot submit a ticket without getting the error I stated even after configuring the email client in .env and config/mail.php

**Comment by PovilasKorop** [comment]
@MikeyUko sorry we don't provide debugging support
